# Streamlit secrets configuration
# Replace the placeholder values with your actual secrets

[gcp]
GCP_PROJECT = "wagon-bootcamp-461109"
BQ_DATASET = "decp_dataset"
BQ_TABLE = "data_clean_bigquery"

[api]
BASE_URL = "https://decp-708609074810.europe-west1.run.app"
ENDPOINT_CLUSTERS = "/api/predict"
ENDPOINT_ESTIMATION = "/api/montant"
ENDPOINT_RAG = "/api/rag"

[api_keys]
MISTRAL_API_KEY = "6lm4UZuSIPlcZDrQGOeEQfi9cu6uLY4f"

[langsmith]
LANGSMITH_TRACING = "true"
LANGSMITH_ENDPOINT = "https://api.smith.langchain.com"
LANGSMITH_API_KEY = "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"
LANGSMITH_PROJECT = "decp_ml"