# Streamlit secrets configuration
# Replace the placeholder values with your actual secrets

[gcp]
GCP_PROJECT="pivotal-base-456812-t7"
BQ_DATASET = "decp_ml"
BQ_TABLE = "data_clean_bigquery"

[gcp_service_account]
type = "service_account"
project_id = "pivotal-base-456812-t7"
private_key_id = "af80c5533c85c31088009bc52b1ea36369f18f7a"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC/SW6cRJ0D1kJX
HaedhNeEr7ItvYkNjsFi/kW0ZosPgSvOSWGZzt0l1wrNSFOLHQHM4EUsXKsu0Tv0
vyGMECYdazW+bxBeI3N68J7eQi3z4zEuX80ZenU7gj1ma30ejdwF9mkAZQdyYI+T
1CjjKQbruwVLREBWGUFongmKj39JbWGel1H+cnxauooNmyytCXATbzqDSI9sIo3x
2PU94lfsyXgFRFqPdAjkmvAe1dl82ToBkb9WWmxsybXSOdFA34gsHs2f1Gm8WRRI
rfxYtIqvzXZWe6viD4Xx2n9o5BAy0fBtgRrXXDiMSS32LjLW31kEQqLFVyg0jp3X
tRSBoHU7AgMBAAECggEACAorknjVypv+RNATw+yZ7FNAH2kIch/uY91BC8CFlry8
nRp7di36IIWFyDQCguXQtg41ChTJAxo7NWG1JMBnAbSIWT0syHAgAepMGxZX/Riu
7/6JzcjWVY53Sy84Xoji1wNQzXnxkq6ZSkLQByAp0M2W/t9a/uNn2uBNkVvPo0PZ
bqa+f4jdwupTbESHehDRP3Yem1OwQlO3e8epj7/AO8AYmeWoxjgSBM63qrowELvG
YY3qJP/Kn2ydTo3y5xzEG0evVlUKCyx8vn+TSfe6A++W23lrT8g6exXGAGyT5Hxj
cbginEpZ8iB53ndZLYV6udyX7Rlh6JnRdVQ+QHyMEQKBgQD3sy9Rmd9o6y/EVv/x
Ch6FzY/SkF1BvUyU8/8WX4Y0bdyb5YNbLVGtm4JMPvodxlJ+N9VKDKGWbF7IBTyK
nvpFlujuQnMqoj5yDl+ML2Nv7YtzMk5js39INz7lxI4g63aEgqmhMIWwWmcmTjkm
zUZfYju/5pxaZnODoiBF6rCukQKBgQDFslNPCihayVv+HlSfiWzQgMMBxIPmqKhb
deoaZ3ZNdSLTHA8A+X/gnh0CuUF5XKtXPnx/bSM9VF2p5Ko9MYRN9q0aJaDIHtdO
oXBVh8ml06CwjyuVHdSqh/qfPxJK0Ux3A3aOSoG/9c4kMZRUrmjzAKfIdR9c7rTR
VOIIGO4lCwKBgQDeTSkdggxYPCLNggsHh75m9VqrbjbT5hFR6T05Fhf6+9Iu86eU
77JLLbKdvTN5/2BPuMoqP/XRa4cQ2mpAOneAdvSryGVVkPCcKjwkMu96J2WsyCxE
HHcSF8rSKTopX0kpmZ6ldEe3Qxsp7LAsG7SZrC7VhiEynJn1PE7ckMlqkQKBgAs5
gcNmFz54WlHGVRWtztDTzr6l8rtA7jYrLryLDUt+kBieajeq8tjFAW6rKA2E9nGA
qb7uambMCHlh80yAKDvo+pEWe9eA8MaVIfSpPgi9SE1eA6J2zCFWkSNDiH1Y/tdv
CecwUcedZDPn4L0iHfFWIzCdfcdgAkI0aJT/HV5bAoGAXxGO5OFbBK8R+yCLkjDk
s3dxXkhOBSsA6cl9HR94HIZmtyfzyC9Xjt2JBw4piW2LIHyScPC2itt6/+cDc9pu
hjfe47Quwyac8aocM7RHq1bgBm28pI0bpWr1cosMn2bCC+XKHGDouaWRGBvVaPOu
F7PifHL5Fp0AVbXzjlnmrrE=
-----END PRIVATE KEY-----'''
client_email = "wagon-ds-bootcamp@pivotal-base-456812-t7.iam.gserviceaccount.com"
client_id = "117011568850301307128"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/wagon-ds-bootcamp%40pivotal-base-456812-t7.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[api]
BASE_URL = "https://decp-708609074810.europe-west1.run.app"
ENDPOINT_CLUSTERS = "/api/predict"
ENDPOINT_ESTIMATION = "/api/montant"
ENDPOINT_RAG = "/api/rag"

[api_keys]
MISTRAL_API_KEY = "6lm4UZuSIPlcZDrQGOeEQfi9cu6uLY4f"

[langsmith]
LANGSMITH_TRACING = "true"
LANGSMITH_ENDPOINT = "https://api.smith.langchain.com"
LANGSMITH_API_KEY = "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"
LANGSMITH_PROJECT = "decp_ml"